<?php
/**
 * Vat
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Billingo API v3
 *
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.13
 * Contact: hello@billingo.hu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * Vat Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Vat
{
    /**
     * Possible values of this enum
     */
    const _0 = '0%';
const _1 = '1%';
const _10 = '10%';
const _11 = '11%';
const _12 = '12%';
const _13 = '13%';
const _14 = '14%';
const _15 = '15%';
const _16 = '16%';
const _17 = '17%';
const _18 = '18%';
const _19 = '19%';
const _2 = '2%';
const _20 = '20%';
const _21 = '21%';
const _22 = '22%';
const _23 = '23%';
const _24 = '24%';
const _25 = '25%';
const _26 = '26%';
const _27 = '27%';
const _3 = '3%';
const _4 = '4%';
const _5 = '5%';
const _6 = '6%';
const _7 = '7%';
const _77 = '7,7%';
const _8 = '8%';
const _9 = '9%';
const AAM = 'AAM';
const AM = 'AM';
const EU = 'EU';
const EUK = 'EUK';
const FAFA = 'F.AFA';
const FAD = 'FAD';
const KAFA = 'K.AFA';
const MAA = 'MAA';
const TAM = 'TAM';
const KK = 'ÁKK';
const THK = 'ÁTHK';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_0,
self::_1,
self::_10,
self::_11,
self::_12,
self::_13,
self::_14,
self::_15,
self::_16,
self::_17,
self::_18,
self::_19,
self::_2,
self::_20,
self::_21,
self::_22,
self::_23,
self::_24,
self::_25,
self::_26,
self::_27,
self::_3,
self::_4,
self::_5,
self::_6,
self::_7,
self::_77,
self::_8,
self::_9,
self::AAM,
self::AM,
self::EU,
self::EUK,
self::FAFA,
self::FAD,
self::KAFA,
self::MAA,
self::TAM,
self::KK,
self::THK,        ];
    }
}
