<?php
/**
 * DocumentExportFilterExtraTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Billingo API v3
 *
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.11
 * Contact: hello@billingo.hu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DocumentExportFilterExtraTest Class Doc Comment
 *
 * @category    Class
 * @description DocumentExportFilterExtra
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentExportFilterExtraTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DocumentExportFilterExtra"
     */
    public function testDocumentExportFilterExtra()
    {
    }

    /**
     * Test attribute "tensoft_vkod"
     */
    public function testPropertyTensoftVkod()
    {
    }

    /**
     * Test attribute "ledger_number"
     */
    public function testPropertyLedgerNumber()
    {
    }

    /**
     * Test attribute "forintsoft_konyvelesi_naplo_szam"
     */
    public function testPropertyForintsoftKonyvelesiNaploSzam()
    {
    }

    /**
     * Test attribute "positive_ledger_number"
     */
    public function testPropertyPositiveLedgerNumber()
    {
    }

    /**
     * Test attribute "negative_ledger_number"
     */
    public function testPropertyNegativeLedgerNumber()
    {
    }

    /**
     * Test attribute "rlb_kata"
     */
    public function testPropertyRlbKata()
    {
    }

    /**
     * Test attribute "rlb_note"
     */
    public function testPropertyRlbNote()
    {
    }

    /**
     * Test attribute "novitax_naplokod"
     */
    public function testPropertyNovitaxNaplokod()
    {
    }

    /**
     * Test attribute "use_gross_values"
     */
    public function testPropertyUseGrossValues()
    {
    }
}
