<?php
/**
 * DocumentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Billingo API v3
 *
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.13
 * Contact: hello@billingo.hu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DocumentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocumentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for archiveDocument
     *
     * Archive a proforma document..
     *
     */
    public function testArchiveDocument()
    {
    }

    /**
     * Test case for cancelDocument
     *
     * Cancel a document.
     *
     */
    public function testCancelDocument()
    {
    }

    /**
     * Test case for createDocument
     *
     * Create a document.
     *
     */
    public function testCreateDocument()
    {
    }

    /**
     * Test case for createDocumentFromProforma
     *
     * Create a document from proforma..
     *
     */
    public function testCreateDocumentFromProforma()
    {
    }

    /**
     * Test case for createModificationDocument
     *
     * Create a modification document..
     *
     */
    public function testCreateModificationDocument()
    {
    }

    /**
     * Test case for deleteDocument
     *
     * Delete a draft..
     *
     */
    public function testDeleteDocument()
    {
    }

    /**
     * Test case for deletePayment
     *
     * Delete all payment history on document.
     *
     */
    public function testDeletePayment()
    {
    }

    /**
     * Test case for documentCopy
     *
     * Copy a document.
     *
     */
    public function testDocumentCopy()
    {
    }

    /**
     * Test case for downloadDocument
     *
     * Download a document in PDF format..
     *
     */
    public function testDownloadDocument()
    {
    }

    /**
     * Test case for getDocument
     *
     * Retrieve a document.
     *
     */
    public function testGetDocument()
    {
    }

    /**
     * Test case for getOnlineSzamlaStatus
     *
     * Retrieve a document Online Számla status.
     *
     */
    public function testGetOnlineSzamlaStatus()
    {
    }

    /**
     * Test case for getPayment
     *
     * Retrieve a payment histroy.
     *
     */
    public function testGetPayment()
    {
    }

    /**
     * Test case for getPublicUrl
     *
     * Retrieve a document download public url..
     *
     */
    public function testGetPublicUrl()
    {
    }

    /**
     * Test case for listDocument
     *
     * List all documents.
     *
     */
    public function testListDocument()
    {
    }

    /**
     * Test case for posPrint
     *
     * Returns a printable POS PDF.
     *
     */
    public function testPosPrint()
    {
    }

    /**
     * Test case for sendDocument
     *
     * Send invoice to given email adresses..
     *
     */
    public function testSendDocument()
    {
    }

    /**
     * Test case for updatePayment
     *
     * Update payment history.
     *
     */
    public function testUpdatePayment()
    {
    }
}
